Repository globaltcad/swing-tree, pull requests merged in 2024-04, with the labels that each got.

#48 45 general api improvements
  docs/img/tutorial/font-with-background-and-foreground-noise.png
  docs/img/tutorial/gradient-styled-font.png
  docs/markdown/Climbing-Swing-Tree.md
  docs/markdown/Font-Styling.md
  src/main/java/swingtree/AbstractDelegate.java
  src/main/java/swingtree/BuilderState.java
  src/main/java/swingtree/SplitButtonDelegate.java
  src/main/java/swingtree/SplitItem.java
  src/main/java/swingtree/UI.java
  src/main/java/swingtree/UIFactoryMethods.java
  src/main/java/swingtree/UIForAnySwing.java
  src/main/java/swingtree/UIForAnyWindow.java
  src/main/java/swingtree/UIForAnything.java
  src/main/java/swingtree/api/Constants.java
  src/main/java/swingtree/api/IconDeclaration.java
  src/main/java/swingtree/api/Layout.java
  src/main/java/swingtree/api/NoiseFunction.java
  src/main/java/swingtree/api/Styler.java
  src/main/java/swingtree/dialogs/ConfirmDialog.java
  src/main/java/swingtree/dialogs/MessageDialog.java
  src/main/java/swingtree/dialogs/OptionsDialog.java
  src/main/java/swingtree/layout/Location.java
  src/main/java/swingtree/layout/Size.java
  src/main/java/swingtree/style/BaseConf.java
  src/main/java/swingtree/style/BorderConf.java
  src/main/java/swingtree/style/ComponentExtension.java
  src/main/java/swingtree/style/ComponentStyleDelegate.java
  src/main/java/swingtree/style/ConicalGradientPaint.java
  src/main/java/swingtree/style/FontConf.java
  src/main/java/swingtree/style/FontPaint.java
  src/main/java/swingtree/style/FontPaintConf.java
  src/main/java/swingtree/style/GradientConf.java
  src/main/java/swingtree/style/ImageConf.java
  src/main/java/swingtree/style/NoiseConf.java
  src/main/java/swingtree/style/NoiseFunctions.java
  src/main/java/swingtree/style/NoiseGradientPaint.java
  src/main/java/swingtree/style/Outline.java
  src/main/java/swingtree/style/ShadowConf.java
  src/main/java/swingtree/style/StyleConf.java
  src/main/java/swingtree/style/StyleConfLayers.java
  src/main/java/swingtree/style/StyleEngine.java
  src/main/java/swingtree/style/StyleInstaller.java
  src/main/java/swingtree/style/StyleRenderer.java
  src/main/java/swingtree/style/StyleUtil.java
  src/main/java/swingtree/style/SvgIcon.java
  src/test/groovy/swingtree/other/Options_Pane_Spec.groovy
  src/test/groovy/swingtree/styles/Individual_Component_Styling_Spec.groovy
  src/test/groovy/swingtree/styles/Invariant_Styles_Spec.groovy
  src/test/groovy/swingtree/styles/Styles_Spec.groovy
  src/test/resources/snapshots/components/custom-text-placement-collage_1_.png
  src/test/resources/snapshots/components/custom-text-placement-collage_2_.png
  src/test/resources/snapshots/components/font-style-with-custom-paint.png
  src/test/resources/snapshots/components/noise-gradients-collage_1_.png
  src/test/resources/snapshots/components/noise-gradients-collage_2_.png
  src/test/resources/snapshots/views/animated-buttons-UI_1_.png
  src/test/resources/snapshots/views/animated-buttons-UI_2_.png
Labels: enhancement

#49 47 missing attr when adding component
  src/main/java/swingtree/UIForAnySwing.java
  src/test/groovy/swingtree/mvvm/MVVM_Example_Spec.groovy
Labels: bug

#51 50 background filter support in style engine
  src/main/java/swingtree/UI.java
  src/main/java/swingtree/UIForAnyButton.java
  src/main/java/swingtree/components/JBox.java
  src/main/java/swingtree/components/JGlassPane.java
  src/main/java/swingtree/components/JIcon.java
  src/main/java/swingtree/components/JSplitButton.java
  src/main/java/swingtree/style/BaseConf.java
  src/main/java/swingtree/style/BoxModelConf.java
  src/main/java/swingtree/style/ComponentExtension.java
  src/main/java/swingtree/style/ComponentStyleDelegate.java
  src/main/java/swingtree/style/DynamicLaF.java
  src/main/java/swingtree/style/FilterConf.java
  src/main/java/swingtree/style/KernelConf.java
  src/main/java/swingtree/style/LayerCache.java
  src/main/java/swingtree/style/LayerRenderConf.java
  src/main/java/swingtree/style/NamedConfigs.java
  src/main/java/swingtree/style/NoiseConf.java
  src/main/java/swingtree/style/Scale.java
  src/main/java/swingtree/style/StylableComponent.java
  src/main/java/swingtree/style/StyleAndAnimationBorder.java
  src/main/java/swingtree/style/StyleConf.java
  src/main/java/swingtree/style/StyleConfLayers.java
  src/main/java/swingtree/style/StyleEngine.java
  src/main/java/swingtree/style/StyleInstaller.java
  src/main/java/swingtree/style/StyleRenderer.java
  src/main/java/swingtree/style/StyleUtil.java
  src/test/groovy/swingtree/examples/Examples_Spec.groovy
  src/test/groovy/swingtree/mvvm/MVVM_Example_Spec.groovy
  src/test/groovy/swingtree/other/Styled_Component_Border_Inset_Spec.groovy
  src/test/groovy/swingtree/styles/Style_Animations_Spec.groovy
  src/test/groovy/swingtree/styles/Style_Installation_Spec.groovy
  src/test/groovy/swingtree/styles/Styles_Spec.groovy
  src/test/java/examples/stylish/GlassUIView.java
  src/test/resources/snapshots/views/glass-style-example-view.png
Labels: enhancement

#52 46 wrong placement of the textfield placeholder
  src/main/java/swingtree/UI.java
  src/main/java/swingtree/style/ComponentAreas.java
  src/main/java/swingtree/style/ComponentConf.java
  src/main/java/swingtree/style/ComponentExtension.java
  src/main/java/swingtree/style/LayerRenderConf.java
  src/main/java/swingtree/style/NamedConfigs.java
  src/main/java/swingtree/style/Outline.java
  src/main/java/swingtree/style/StyleAndAnimationBorder.java
  src/main/java/swingtree/style/StyleConfLayers.java
  src/main/java/swingtree/style/StyleInstaller.java
  src/main/java/swingtree/style/StyleRenderer.java
  src/test/groovy/swingtree/other/Styled_Component_Border_Inset_Spec.groovy
Labels: bug

#54 53 set method for border color overridden by styleinstaller
  src/main/java/swingtree/style/StyleInstaller.java
Labels: bug

#57 56 improved documentation
  docs/img/tutorial/glassy-tissue-background.png
  docs/img/tutorial/scaled-glassy-tissue-background.png
  docs/markdown/Background-Filtering.md
  docs/markdown/Climbing-Swing-Tree.md
  src/main/java/swingtree/AbstractDelegate.java
  src/main/java/swingtree/ComponentDragEventDelegate.java
  src/main/java/swingtree/Render.java
  src/main/java/swingtree/SplitButtonDelegate.java
  src/main/java/swingtree/SplitItem.java
  src/main/java/swingtree/SplitItemDelegate.java
  src/main/java/swingtree/UI.java
  src/main/java/swingtree/UIFactoryMethods.java
  src/main/java/swingtree/UIForAnything.java
  src/main/java/swingtree/UIForIcon.java
  src/main/java/swingtree/UIForSeparator.java
  src/main/java/swingtree/UIForSlider.java
  src/main/java/swingtree/api/IconDeclaration.java
  src/main/java/swingtree/api/model/TableMapDataSource.java
  src/main/java/swingtree/dialogs/ConfirmDialog.java
  src/main/java/swingtree/layout/Size.java
  src/main/java/swingtree/style/Arc.java
  src/main/java/swingtree/style/BaseConf.java
  src/main/java/swingtree/style/BorderConf.java
  src/main/java/swingtree/style/BoxModelConf.java
  src/main/java/swingtree/style/ComponentAreas.java
  src/main/java/swingtree/style/ComponentStyleDelegate.java
  src/main/java/swingtree/style/DimensionalityConf.java
  src/main/java/swingtree/style/FontConf.java
  src/main/java/swingtree/style/GradientConf.java
  src/main/java/swingtree/style/ImageConf.java
  src/main/java/swingtree/style/LayerRenderConf.java
  src/main/java/swingtree/style/LayoutConf.java
  src/main/java/swingtree/style/NoiseConf.java
  src/main/java/swingtree/style/Outline.java
  src/main/java/swingtree/style/ShadowConf.java
  src/main/java/swingtree/style/StyleConfLayer.java
  src/main/java/swingtree/style/StyleRenderer.java
  src/main/java/swingtree/style/StyleUtil.java
  src/main/java/swingtree/style/TextConf.java
Labels: documentation

#58 55 combo box on selection event fired when user types something
  src/main/java/swingtree/AbstractComboModel.java
  src/main/java/swingtree/UIForCombo.java
  src/test/groovy/swingtree/styles/Style_Sheet_Spec.groovy
  src/test/groovy/swingtree/styles/Styles_Spec.groovy
  src/test/resources/snapshots/components/custom-font-JTextArea_3_.png
  src/test/resources/snapshots/components/custom-text-placement-collage_3_.png
  src/test/resources/snapshots/components/font-style-inheritance_3_.png
  src/test/resources/snapshots/components/font-style-with-custom-paint_1_.png
  src/test/resources/snapshots/components/font-style-with-custom-paint_2_.png
  src/test/resources/snapshots/components/left-to-right-shaded-JTextArea_3_.png
  src/test/resources/snapshots/components/rounded-green-JLabel_1_.png
  src/test/resources/snapshots/components/rounded-green-JLabel_2_.png
  src/test/resources/snapshots/views/animated-buttons-UI_3_.png
  src/test/resources/snapshots/views/made-with-SwingTree_4_.png
  src/test/resources/snapshots/views/simple-form-UI_3_.png
Labels: bug

#60 Bump Sprouts Version
  build.gradle
Labels: enhancement

#67 Add text padding to the right
  src/main/java/swingtree/components/JSplitButton.java
Labels: bug

#69 fix plain buttonwith a custom painter is opaque
  src/main/java/swingtree/UIForAnyButton.java
  src/main/java/swingtree/UIForAnySwing.java
  src/main/java/swingtree/style/StyleInstaller.java
  src/test/groovy/swingtree/styles/Opaqueness_Styles_Spec.groovy
Labels: bug

#72 71 method brighterby in color is inverted
  src/main/java/swingtree/UI.java
  src/test/groovy/swingtree/styles/Color_Spec.groovy
Labels: bug

#74 73 introduce animationstate sub progress slicing
  src/main/java/swingtree/CustomCleaner.java
  src/main/java/swingtree/OptionalUI.java
  src/main/java/swingtree/SplitButtonDelegate.java
  src/main/java/swingtree/SplitItemDelegate.java
  src/main/java/swingtree/UIFactoryMethods.java
  src/main/java/swingtree/UIForProgressBar.java
  src/main/java/swingtree/animation/AnimationState.java
  src/main/java/swingtree/animation/Progress.java
  src/main/java/swingtree/api/IconDeclaration.java
  src/main/java/swingtree/dialogs/ConfirmDialog.java
  src/main/java/swingtree/dialogs/OptionsDialog.java
  src/main/java/swingtree/layout/Bounds.java
  src/main/java/swingtree/style/Arc.java
  src/main/java/swingtree/style/NamedConfigs.java
Labels: enhancement
