Repository globaltcad/swing-tree, pull requests merged in 2024-12, with the labels that each got.

#233 Fix Potential Memory Leaks in Cleaner Actions
  src/main/java/swingtree/CustomCleaner.java
  src/main/java/swingtree/UIForAnything.java
Labels: enhancement

#235 Check if component is showing
  src/main/java/swingtree/EnterExitComponentBoundsEventDispatcher.java
Labels: bug, approved

#240 Fix an Index of -1 can Lead to Tab Selection being True, Causing Endless Recursion
  src/main/java/swingtree/UIForTabbedPane.java
Labels: bug
